apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: gitops
spec:
  destination:
    namespace: gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/helm/app-of-apps
    repoURL: https://github.com/Ujstor/k3s-multi-node-iac
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
