plausible:
  plausible-analytics:
    baseURL: https://plausible-analytics.k8s0.ujstor.com
    disableRegistration: false

  customIngress:
    enabled: true
    hosts:
      - host: plausible-analytics.k8s0.ujstor.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: plausible-analytics-tls
        hosts:
          - plausible-analytics.k8s0.ujstor.com
