---
- name: Get list of mounted devices under /mnt
  shell: findmnt -l -n -o SOURCE,TARGET | grep '/mnt' || true
  register: mounted_devices
  changed_when: false

- name: Show mounted devices (debug)
  debug:
    var: mounted_devices.stdout_lines

- name: Force unmount all volumes under /mnt
  shell: "umount -f {{ item.split()[1] }}"
  with_items: "{{ mounted_devices.stdout_lines }}"
  when: mounted_devices.stdout_lines | length > 0
  register: umount_result
  failed_when: false

- name: Get list of valid block devices
  shell: |
    lsblk -pndo NAME,TYPE | grep 'disk' | awk '{print $1}' | grep -v -e '^/dev/sr[0-9]' -e '^/dev/loop'
  register: block_devices
  changed_when: false

- name: Show block devices to be wiped (debug)
  debug:
    var: block_devices.stdout_lines

- name: Wipe filesystem signatures
  block:
    - name: Wipe filesystem signatures
      command: wipefs -af {{ item }}
      with_items: "{{ block_devices.stdout_lines }}"
      when: 
        - item is regex("^/dev/(s|v|x)d[a-z]$")
        - item not in ansible_mounts | map(attribute='device') | list
        - "'boot' not in item"

    - name: Zero first 100MB of each device
      command: dd if=/dev/zero of={{ item }} bs=1M count=100
      with_items: "{{ block_devices.stdout_lines }}"
      when:
        - item is regex("^/dev/(s|v|x)d[a-z]$")
        - item not in ansible_mounts | map(attribute='device') | list
        - "'boot' not in item"

- name: Clear partition tables
  command: sgdisk --zap-all {{ item }}
  with_items: "{{ block_devices.stdout_lines }}"
  when:
    - item is regex("^/dev/(s|v|x)d[a-z]$")
    - item not in ansible_mounts | map(attribute='device') | list
    - "'boot' not in item"

- name: Wait for all device changes to settle
  command: udevadm settle
  changed_when: false

- name: Clear device mapper entries
  command: dmsetup remove_all --force
  failed_when: false
  changed_when: true

- name: Final wipe of devices
  command: wipefs -af {{ item }}
  with_items: "{{ block_devices.stdout_lines }}"
  when:
    - item is regex("^/dev/(s|v|x)d[a-z]$")
    - item not in ansible_mounts | map(attribute='device') | list
    - "'boot' not in item"
