apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-rook-ceph-operator
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/hook-dependency: system-cert-manager
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: cluster-bootstrap
  source:
    path: gitops/helm/system/rook-ceph-operator
    repoURL: https://github.com/Ujstor/k8s-k3s-multi-node-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: rook-ceph-operator
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
