apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-argocd
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  destination:
    namespace: gitops
    server: https://kubernetes.default.svc
  project: cluster-bootstrap
  source:
    path: gitops/helm/system/argocd
    repoURL: https://github.com/Ujstor/k3s-multi-node-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: argocd
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
