apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-todo-go-htmx
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "16"
    argocd.argoproj.io/hook-dependency: system-rook-ceph-cluster
spec:
  destination:
    namespace: todo-go-htmx
    server: https://kubernetes.default.svc
  project: cluster-bootstrap
  source:
    path: gitops/helm/apps/todo-go-htmx
    repoURL: https://github.com/Ujstor/k3s-multi-node-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: todo-go-htmx
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
